name: Run CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tf-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_ver: ["3.8", "3.9", "3.10", "3.11"]
        tf_ver: ["2.10", "2.11", "2.12", "2.13"]
        exclude:
          - py_ver: "3.11"
            tf_ver: "2.10"
          - py_ver: "3.11"
            tf_ver: "2.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.py_ver}}
      - name: Install dependencies
        run: |
          pip install tensorflow==${{matrix.tf_ver}}
          pip install -r requirements_test.txt
      - name: Run pytest
        run: |
          pytest sony_custom_layers/keras
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        run: |
          ./install-pre-commit.sh
          pre-commit run --all

      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*
    
